spring:

  output:
    ansi:
      enabled: always
  jmx:
    enabled: false
    default-domain: com.aire.ux
  main:
    allow-bean-definition-overriding: true
#    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
  application:
    admin:
      jmx-name: org.springframework.boot:type=Admin,name=ZephyrCoreApplication
      enabled: false

ui-service:
  init:
    listener: true
logging:
  config: classpath:config/logback-spring.xml

vaadin:
  whitelisted-packages: io.sunshower.zephyr,io.sunshower.cloud.studio,io.sunshower.zephyr.ui