name: Java CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Maven Dependencies
      run: >-
        mvn install deploy -f bom
        --settings bom/settings/settings.xml
        -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
        -Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}

    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 7.0.2
        arguments: >-
          assemble build pTML publish sA
          -i
          -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}} --stacktrace


